### ISSUE TITLE
What should I do after installing the plugin on my WordPress plugin manage page?

### ISSUE THREAD

**Issue by jasonbanjui** [gis-ops/md-github-wordpress#10]
When I install this plugin, I have no idea how to go on using it. Maybe I should add the code you said to my article? See it like not work. I am so sorry for ignorance. Can you create a course to help another study how can apply it？ I think this plugin you produced is cool.  I look ahead to your reply.  :+1:  :)

**Comment by nilsnolde** [comment]
Hi, sorry man, I should've marked this plugin as deprecated weeks ago. I'll do so now.

However, good news: there's a new (and much superior) plugin here:
https://github.com/gis-ops/wordpress-markdown-git
https://wordpress.org/plugins/documents-from-git/

I also hope the README is better done:) I'll close here. If you still have problems with the newer plugin, don't hesitate to ask a question. And please try to be more specific, i.e. what did you try and what didn't work, ideally with an error or similar. But there's also an issue template which will guide you a little.
