### ISSUE TITLE
after installing the plugin the entire site shifts right

### ISSUE THREAD

**Issue by FarisZR** [gis-ops/md-github-wordpress#11]
hi i have installed the plugin and was looking up to using it,
but when i enable it the entire website shifts right.
the control panel also shifted, and i cant disable the plugin without resizing to mobile size
![image](https://user-images.githubusercontent.com/35614734/85956379-25ddaa00-b98e-11ea-877c-b5c56b06040d.png)
thats how the plujgin sheet looks it cut behind the sidebar.
the website is using arabic for its default language.
wordpress : 5.4.2
and one last question does the plugin support RTL?

**Comment by nilsnolde** [comment]
This plugin is deprecated and officially closed, you shouldn't be able to still install this. Please look at the README and use the other plugin.

**Comment by FarisZR** [comment]
> This plugin is deprecated and officially closed, you shouldn't be able to still install this. Please look at the README and use the other plugin.
oh thats the wrong repository sorry!
