### ISSUE TITLE
Relative image paths in repository?

### ISSUE THREAD

**Issue by tenari-jp** [gis-ops/md-github-wordpress#4]
I want to view images in repository with relative path
e.g.
```
![myImage](../assets/01_img.jpg)
```
Should I write absolute paths...?

**Comment by nilsnolde** [comment]
Well, that depends. It can be relative only if it's the same relative path to the image exists on the machine where you're hosting Wordpress. Which it likely is not.

What we do for example is refer to Github's raw user content, e.g. 
https://github.com/gis-ops/tutorials/raw/master/qgis/static/img/quick_api_interactive_ui.png

IMHO that even better than Wordpress media links, Github will always stay, so it's really a permalink.
