### ISSUE TITLE
Rendering of boarder with dashed lines

### ISSUE THREAD

**Issue by troppens** [gis-ops/md-github-wordpress#5]
I am using the nbconvert plugin and I am happy that I found this plugin for embedding GitHub markdown in my web page. Great work!

It would be nice to add a capability to render a frame with dashed borders to contrast embedded content like nbconvert does. The first image below shows the current rendering. In the second image I have added a frame with dashed lines in a graphic program.

Do you plan such an enhancement? I am envisioning an additional shortcode that renders the frame with dashed lines, the check-out banner, and the markdown content.

Would you accept a pull request, if I submit such an enhancement? I have no experience with WordPress plugins and PHP but would give it a try.

![image](https://user-images.githubusercontent.com/22422468/67584640-62496e00-f74e-11e9-8d45-b949418a08ad.png)
![image](https://user-images.githubusercontent.com/22422468/67584861-ccfaa980-f74e-11e9-8265-042c2431f34e.png)

**Comment by nilsnolde** [comment]
If the capability is embedded in a shortcode or smth flexible so I don't have to use it, sure:) You could add e.g. a `border-class` as shortcode if you want, with the value being CSS and then add it as inline style in PHP. That's in fact very easy, give it a try. This is my first plugin too, built on top of nbconvert. 

Ugly code, so pls no judgment;)

**Comment by troppens** [comment]
The added code should not interfere with your existing code. It would be nice if you could mention me somewhere as contributor, but I didn't know where to put it.

Thanks a again for the nice plug-in. Very useful for me.

**Comment by nilsnolde** [comment]
Hi @troppens ,

I will deprecate this plugin very soon and instead do a "Markdown Git" plugin to support more platforms than just Github, as there's been some requests for that. The existing plugin won't disappear but also won't be maintained anymore.

I'll see if I can make it flexible enough to enable the input of a custom CSS class to wrap the contents of the post in a parent `<div>`, similar to what you did, but as dynamic shortcode or so. Will have to think about it a little. Will happen in the next 1-2 weeks, just wanted to give you a heads-up.

**Comment by troppens** [comment]
Hi @nilsnolde , thanks for the heads-up. Looking forward to try the new plug-in.

**Comment by planetahuevo** [comment]
@nilsnolde I was planning to use this for a project now (just a couple of pages so I can do it manually in the meantime).
Do you recommend to wait for the new one? 
Do you have an ETA for that?
Thanks

**Comment by nilsnolde** [comment]
It's actually done: https://github.com/gis-ops/wordpress-markdown-git. I'm just waiting for the client's approval, who sponsored the Bitbucket integration initially. Will deprecate here when it's done in max a week.

Also replaces the `nbconvert` plugin from Andy Challis. 

https://github.com/gis-ops/wordpress-markdown-git
https://github.com/gis-ops/wordpress-markdown-git/issues/3

**Comment by planetahuevo** [comment]
Oh, fantastic. 
This is great. 
Thank you very much!
