### ISSUE TITLE
Just does not work

### ISSUE THREAD

**Issue by adamth0mps0n** [gis-ops/md-github-wordpress#7]
I have the latest version of WordPress.. 
I Generated a GitHub access token 
Put the required link in the post and I just get a blank page

[md_github token=my_token_key url=https://github.com/holochain/lib3h/blob/edge/CHANGELOG.md]

**Comment by nilsnolde** [comment]
Just works. For me at least. With your exact shortcode (plus my token). Double-check your token!

https://gis-ops.com/test/

Will take that down in 2 hours.
