### ISSUE TITLE
Relative embedded images URLs are resolved incorrectly

### ISSUE THREAD

**Issue by huksley** [gis-ops/md-github-wordpress#8]
Hi, thanks for this plugin, it works good with Markdown content
but if I have an embedded image, like this:
```markdown
![Sample image](191001_Homepage_hero_image_FI_EN.png)
```

The `img` tag rendered have relative link to Wordpress repo, i.e.
```html
<p>
<a target="_blank" rel="noopener noreferrer" href="191001_Homepage_hero_image_FI_EN.png">
<img src="191001_Homepage_hero_image_FI_EN.png" alt="Sample image" style="max-width:100%;">
</a>
</p>
```

as a result, images are not displayed.

**Comment by nilsnolde** [comment]
Hi,

you'll have to either:

- provide the fully qualified image URL of your hosted Wordpress image
- store the image alongside your document on Github and specify that full URL 

I usually do the latter. Github has better servers than our shared hosts;)

E.g. this post features an image and is located in the Github repo path `./qgis' and I created a folder in `./qgis/static/img` where I put all the images and reference their URLs in the Markdown. You can see the URL I used when you hover over the image.
