### ISSUE TITLE
Request: Caching HTML

### ISSUE THREAD

**Issue by eblabs** [gis-ops/md-github-wordpress#9]
Hi,
Thanks for the great plugin! I just had a couple of questions/Requests if possible.

Tokens
*  I just wanted to ask about separating the token from the shortcode maybe these could be defined someplace else? The tokens aren't that permanent and it would be a pain to change tokens in all posts if it ever came up. 

Caching
* It seems like all of the api calls might be too many. Would you consider adding the possibility of having an html cache system for the rendered md? Maybe it could be possible reduce lookups to max once an hour, or some other amount of time.

Thanks again for all your hard work on this plugin, its great!

**Comment by nilsnolde** [comment]
Hi,

note, this plugin is virtually deprecated. This one will take its place:
https://github.com/gis-ops/wordpress-markdown-git

It's not published yet, but I intend to do that over the next week. And I had exactly the same thoughts  :smile: :

https://github.com/gis-ops/wordpress-markdown-git/issues/4
https://github.com/gis-ops/wordpress-markdown-git/issues/5

They're both still open and I'd really appreciate some help including it in the AP Admin area. Don't really wanna open the UI box myself;)

**Comment by eblabs** [comment]
Thanks for the quick reply @nilsnolde !

Sounds great, I'm not much help on the coding side (unless its python or c#).  Would it be possible to have a user config file for now until the UI gets figured out? At least for tokens and cache expiry settings.

**Comment by nilsnolde** [comment]
Yeah, that's maybe a good idea. I'll see if I can add a JSON file to access over the "Plugin Editor" UI. Should be pretty easy.

**Comment by nilsnolde** [comment]
And done @eblabs . Give it a spin if you want:
https://github.com/gis-ops/wordpress-markdown-git#global-attributes

**Comment by eblabs** [comment]
Cool checking now. btw, how does the "limit" attribute work? Is this time? or something else?

**Comment by eblabs** [comment]
I'm getting a "500 - Server Error". Any ideas?

**Comment by nilsnolde** [comment]
> how does the "limit" attribute work?

https://github.com/gis-ops/wordpress-markdown-git#attributes

> I'm getting a "500 - Server Error". Any ideas?

Not without any more information.. Who's saying that? Wordpress, the plugin, i.e. post? what's the URL? Please consider opening an issue at the actual repo.

**Comment by eblabs** [comment]
Thanks, adding a bug report now :)
